name: Periodic health check

on:
  push:
    branches:
      - main
  
jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Run health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-ogm4.onrender.com
          max-attempts: 3
      - name: test health check success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Health check passed"
          color: 0x9FE2BF
      - name: test health check failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Health check failed"
          color: 0xF08080